pkgname  = "models"
output   = "persistence/models"
wipe     = true
no-tests = true

[psql]
  dbname = "golangservice"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "password"
  sslmode = "disable"
  blacklist = ["schema_migrations"]