on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: ./do.sh lint
      - name: Build
        run: ./do.sh build
      - name: Test
        run: ./do.sh test
  containerise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: ./do.sh build_container